modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="test"
version="1.0.0"
displayName="Ultimate Additions"
displayURL="https://mcreator.net"
credits="Created using the MCreator mod maker - https://mcreator.net/about"
authors="Jelzox, bretchou"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.test]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.test]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

