modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ultad"
version="1.0.0"
displayName="Ultimate Additions"
displayURL="https://mcreator.net"
credits="Created using the MCreator mod maker - https://mcreator.net/about"
authors="Jelzox, bretchou"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ultad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



